disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
included:
  - Journal App
excluded:
  - Pods
  - Journal App/Generated
line_length:
  warning: 120
  error: 200
function_body_length:
  warning: 50
  error: 100
cyclomatic_complexity:
  warning: 10
  error: 20
